### ISSUE TITLE
Sometimes after it is connecting and loading into the main app, the loading transparency overlay will remain, and everything will be grey

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerAir#5]
I had this happen twice on my iPhone and once on my iPad: https://i.imgur.com/C5kUCYo.png

**Comment by J2Kbr** [comment]
Also happened with me few times. After researching, turned out the issue is with the Qt Framework used by Gtuner Air (not with my code). Soon I will be updating the framework version and expect/hope this to be fixed. I am closing this issue as there is nothing I can do on the Gtuner Air source code to fix.
